AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  OrderProcessor:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: cmd/api/main.go
      Handler: main
      Runtime: go1.x
      Policies:
        - AmazonAPIGatewayInvokeFullAccess
        - AmazonSQSFullAccess

  OrderApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title: Order Processor API
        paths:
          /order-processor:
            post:
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OrderProcessor.Arn}/invocations
              responses: {}
              parameters: []
              consumes: []
              produces: []
        x-amazon-apigateway-binary-media-types:
          - '*/*'

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${OrderApi}.execute-api.${AWS::Region}.amazonaws.com/prod/order-processor"
